version: 2

sphinx:
  builder: html
  configuration: python-libdaw/docs/source/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
    rust: "1.78"

python:
  install:
    - requirements: python-libdaw/docs/requirements.txt
    - method: pip
      path: python-libdaw
