version: 2

sphinx:
  builder: html
  configuration: python-libdaw/docs/source/conf.py

build:
  os: ubuntu-lts-latest
  apt_packages:
    - build-essential
    - libasound2-dev
  tools:
    python: latest
    rust: latest

python:
  install:
    - requirements: python-libdaw/docs/requirements.txt
    - method: pip
      path: python-libdaw
