[workspace]

resolver = '2'

members = [
  'libdaw',
  'ludaw',
]

[workspace.package]
authors = ["Taylor C. Richberger"]
repository = 'https://codeberg.org/Taywee/libdaw'
license-file = 'LICENSE'
readme = 'README.md'
