from typing import Any, Self
from python.libdaw.time import Timestamp

class Beat:
    def __init__(self, value: float) -> None: ...
    def __lt__(self, other: Self) -> bool: ...
    def __le__(self, other: Self) -> bool: ...
    def __eq__(self, other: Self) -> bool: ...
    def __ne__(self, other: Self) -> bool: ...
    def __gt__(self, other: Self) -> bool: ...
    def __ge__(self, other: Self) -> bool: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, memo: dict[Any, Any]) -> Self: ...
    @property
    def value(self) -> float: ...

class BeatsPerMinute:
    def __init__(self, value: float) -> None: ...
    def __lt__(self, other: Self) -> bool: ...
    def __le__(self, other: Self) -> bool: ...
    def __eq__(self, other: Self) -> bool: ...
    def __ne__(self, other: Self) -> bool: ...
    def __gt__(self, other: Self) -> bool: ...
    def __ge__(self, other: Self) -> bool: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, memo: dict[Any, Any]) -> Self: ...
    @property
    def value(self) -> float: ...

class TempoInstruction:
    def __init__(self, beat: Beat, tempo: BeatsPerMinute) -> None: ...
    def __lt__(self, other: Self) -> bool: ...
    def __le__(self, other: Self) -> bool: ...
    def __eq__(self, other: Self) -> bool: ...
    def __ne__(self, other: Self) -> bool: ...
    def __gt__(self, other: Self) -> bool: ...
    def __ge__(self, other: Self) -> bool: ...
    def __copy__(self) -> Self: ...
    def __deepcopy__(self, memo: dict[Any, Any]) -> Self: ...

    @property
    def beat(self) -> Beat: ...

    @property
    def tempo(self) -> BeatsPerMinute: ...

class Metronome:
    def __init__(self) -> None: ...
    def add_tempo_instruction(self, instruction: TempoInstruction) -> None: ...
    def beat_to_time(self) -> Timestamp: ...
