from collections.abc import MutableMapping
from datetime import timedelta
from typing import Any

class Duration:
    def __init__(self, seconds: float | timedelta) -> None: ...
    def seconds(self) -> float: ...
    def timedelta(self) -> timedelta: ...
    def __hash__(self) -> int: ...
    def __lt__(self, other: Duration) -> bool: ...
    def __le__(self, other: Duration) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __gt__(self, other: Duration) -> bool: ...
    def __ge__(self, other: Duration) -> bool: ...
    def __copy__(self) -> Duration: ...
    def __deepcopy__(self, memo: MutableMapping[Any, Any]) -> Duration: ...

class Time:
    def __init__(self, seconds: float | timedelta) -> None: ...
    def seconds(self) -> float: ...
    def timedelta(self) -> timedelta: ...
    def __hash__(self) -> int: ...
    def __lt__(self, other: Time) -> bool: ...
    def __le__(self, other: Time) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __gt__(self, other: Time) -> bool: ...
    def __ge__(self, other: Time) -> bool: ...
    def __copy__(self) -> Time: ...
    def __deepcopy__(self, memo: MutableMapping[Any, Any]) -> Time: ...

class Timestamp:
    def __init__(self, seconds: float | timedelta) -> None: ...
    def seconds(self) -> float: ...
    def timedelta(self) -> timedelta: ...
    def __hash__(self) -> int: ...
    def __lt__(self, other: Timestamp) -> bool: ...
    def __le__(self, other: Timestamp) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __gt__(self, other: Timestamp) -> bool: ...
    def __ge__(self, other: Timestamp) -> bool: ...
    def __copy__(self) -> Timestamp: ...
    def __deepcopy__(self, memo: MutableMapping[Any, Any]) -> Timestamp: ...
